-- MySQL Script generated by MySQL Workbench
-- Thu Nov 15 14:41:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoUsuario` (
  `rol` ENUM('AdmSistemas', 'AdmEstudios', 'Encuestador', 'Analista') NOT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  `tipoUsuario_rol` ENUM('AdmSistemas', 'AdmEstudios', 'Encuestador', 'Analista') NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipoUsuario1_idx` (`tipoUsuario_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_rol`)
    REFERENCES `mydb`.`tipoUsuario` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `idestudio` INT NOT NULL,
  `encuestador` VARCHAR(45) NOT NULL,
  `analista` VARCHAR(45) NOT NULL,
  `tipodeestudio` VARCHAR(45) NULL,
  `nombredeestudio` VARCHAR(45) NULL,
  PRIMARY KEY (`idestudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuestionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cuestionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cuestionario` (
  `idcuestionario` INT NOT NULL,
  `cuestionario` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `idestudio` INT NOT NULL,
  PRIMARY KEY (`idcuestionario`),
  INDEX `fk_cuestionario_estudio1_idx` (`idestudio` ASC) VISIBLE,
  CONSTRAINT `fk_cuestionario_estudio1`
    FOREIGN KEY (`idestudio`)
    REFERENCES `mydb`.`estudio` (`idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipodeReactivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipodeReactivo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipodeReactivo` (
  `idtipodeReactivo` INT NOT NULL,
  PRIMARY KEY (`idtipodeReactivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reactivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reactivo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reactivo` (
  `idreactivo` INT NOT NULL,
  `reactivo` VARCHAR(45) NOT NULL,
  `tiporeactivo` VARCHAR(45) NOT NULL,
  `idcuestionario` INT NOT NULL,
  `idestudio` INT NOT NULL,
  `tipodeReactivo_idtipodeReactivo` INT NOT NULL,
  PRIMARY KEY (`idreactivo`),
  INDEX `fk_reactivo_cuestionario1_idx` (`idcuestionario` ASC, `idestudio` ASC) VISIBLE,
  INDEX `fk_reactivo_tipodeReactivo1_idx` (`tipodeReactivo_idtipodeReactivo` ASC) VISIBLE,
  CONSTRAINT `fk_reactivo_cuestionario1`
    FOREIGN KEY (`idcuestionario` , `idestudio`)
    REFERENCES `mydb`.`cuestionario` (`idcuestionario` , `idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reactivo_tipodeReactivo1`
    FOREIGN KEY (`tipodeReactivo_idtipodeReactivo`)
    REFERENCES `mydb`.`tipodeReactivo` (`idtipodeReactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`respuestas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`respuestas` (
  `idrespuestas` INT NOT NULL,
  `respuestas` VARCHAR(250) NULL,
  `idreactivo` INT NOT NULL,
  `idcuestionario` INT NOT NULL,
  `idestudio` INT NOT NULL,
  PRIMARY KEY (`idrespuestas`),
  INDEX `fk_respuestas_reactivo1_idx` (`idreactivo` ASC, `idcuestionario` ASC, `idestudio` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_reactivo1`
    FOREIGN KEY (`idreactivo` , `idcuestionario` , `idestudio`)
    REFERENCES `mydb`.`reactivo` (`idreactivo` , `idcuestionario` , `idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asignado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asignado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asignado` (
  `idusuario` INT NOT NULL,
  `idestudio` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idestudio`),
  INDEX `fk_usuario_has_estudio_estudio1_idx` (`idestudio` ASC) VISIBLE,
  INDEX `fk_usuario_has_estudio_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_estudio_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_estudio_estudio1`
    FOREIGN KEY (`idestudio`)
    REFERENCES `mydb`.`estudio` (`idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuestionarioContestado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cuestionarioContestado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cuestionarioContestado` (
  `cuestionario_idcuestionario` INT NOT NULL,
  `idcontestado` INT NOT NULL,
  `asignado_idusuario` INT NOT NULL,
  `asignado_idestudio` INT NOT NULL,
  PRIMARY KEY (`idcontestado`),
  INDEX `fk_cuestionarioContestado_cuestionario1_idx` (`cuestionario_idcuestionario` ASC) VISIBLE,
  INDEX `fk_cuestionarioContestado_asignado1_idx` (`asignado_idusuario` ASC, `asignado_idestudio` ASC) VISIBLE,
  CONSTRAINT `fk_cuestionarioContestado_cuestionario1`
    FOREIGN KEY (`cuestionario_idcuestionario`)
    REFERENCES `mydb`.`cuestionario` (`idcuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuestionarioContestado_asignado1`
    FOREIGN KEY (`asignado_idusuario` , `asignado_idestudio`)
    REFERENCES `mydb`.`asignado` (`idusuario` , `idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuestadeCampo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`respuestadeCampo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`respuestadeCampo` (
  `idrespuestadeCampo` INT NOT NULL,
  `idestudio` INT NOT NULL,
  `idrespuestas` INT NOT NULL,
  `idreactivo` INT NOT NULL,
  `idcuestionario` INT NOT NULL,
  `respuestas_reactivo_cuestionario_estudio_idestudio` INT NOT NULL,
  PRIMARY KEY (`idrespuestadeCampo`),
  INDEX `fk_respuestadeCampo_cuestionarioContestado1_idx` (`idestudio` ASC) VISIBLE,
  INDEX `fk_respuestadeCampo_respuestas1_idx` (`idrespuestas` ASC, `idreactivo` ASC, `idcuestionario` ASC, `respuestas_reactivo_cuestionario_estudio_idestudio` ASC) VISIBLE,
  CONSTRAINT `fk_respuestadeCampo_cuestionarioContestado1`
    FOREIGN KEY (`idestudio`)
    REFERENCES `mydb`.`cuestionarioContestado` (`idcontestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestadeCampo_respuestas1`
    FOREIGN KEY (`idrespuestas` , `idreactivo` , `idcuestionario` , `respuestas_reactivo_cuestionario_estudio_idestudio`)
    REFERENCES `mydb`.`respuestas` (`idrespuestas` , `idreactivo` , `idcuestionario` , `idestudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`info_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`info_usuario` (
  `nombre(s)` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `matricula` INT NULL,
  `direccion` VARCHAR(250) NULL,
  `telefono` INT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_info_usuario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
