-- MySQL Script generated by MySQL Workbench
-- sáb 17 nov 2018 23:15:42 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Encuestas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Encuestas` ;

-- -----------------------------------------------------
-- Schema Encuestas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Encuestas` ;
USE `Encuestas` ;

-- -----------------------------------------------------
-- Table `Encuestas`.`TIPOUSUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`TIPOUSUARIO` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`TIPOUSUARIO` (
  `Rol` ENUM("Administrador de Sistema", "Administrador de Estudio", "Encuestador", "Analista") NOT NULL,
  PRIMARY KEY (`Rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `Rol_UNIQUE` ON `Encuestas`.`TIPOUSUARIO` (`Rol` ASC);


-- -----------------------------------------------------
-- Table `Encuestas`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`USUARIOS` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Contrasena` VARCHAR(100) NOT NULL,
  `Rol` ENUM("Administrador de Sistema", "Administrador de Estudio", "Encuestador", "Analista") NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_USUARIOS_TIPOUSUARIO1`
    FOREIGN KEY (`Rol`)
    REFERENCES `Encuestas`.`TIPOUSUARIO` (`Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
PACK_KEYS = DEFAULT;

CREATE UNIQUE INDEX `id_UNIQUE` USING BTREE ON `Encuestas`.`USUARIOS` (`Id`);

CREATE INDEX `fk_USUARIOS_TIPOUSUARIO1_idx` ON `Encuestas`.`USUARIOS` (`Rol` ASC);


-- -----------------------------------------------------
-- Table `Encuestas`.`INFO_USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`INFO_USUARIOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`INFO_USUARIOS` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Edad` INT NOT NULL,
  `Matricula` INT NOT NULL,
  `Direccion` VARCHAR(250) NULL,
  `Telefono` INT NULL,
  `Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id`, `Id_Usuario`),
  CONSTRAINT `fk_Info_Usuarios_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `Encuestas`.`USUARIOS` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE INDEX `fk_Info_Usuarios_Usuarios1_idx` ON `Encuestas`.`INFO_USUARIOS` (`Id_Usuario` ASC);

CREATE UNIQUE INDEX `Id_UNIQUE` ON `Encuestas`.`INFO_USUARIOS` (`Id` ASC) ;

CREATE UNIQUE INDEX `IdUsuarios_UNIQUE` ON `Encuestas`.`INFO_USUARIOS` (`Id_Usuario` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`ESTUDIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`ESTUDIOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`ESTUDIOS` (
  `idEstudio` INT NOT NULL AUTO_INCREMENT,
  `Estudio` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(100) NOT NULL,
  `Encuestador` VARCHAR(100) NOT NULL,
  `Analista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEstudio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `idEstudio_UNIQUE` ON `Encuestas`.`ESTUDIOS` (`idEstudio` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`ASIGNADOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`ASIGNADOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`ASIGNADOS` (
  `IdEstudio` INT NOT NULL,
  `IdUsuarios` INT NOT NULL,
  PRIMARY KEY (`IdEstudio`, `IdUsuarios`),
  CONSTRAINT `fk_Estudio_has_Usuarios_Estudio1`
    FOREIGN KEY (`IdEstudio`)
    REFERENCES `Encuestas`.`ESTUDIOS` (`idEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudio_has_Usuarios_Usuarios1`
    FOREIGN KEY (`IdUsuarios`)
    REFERENCES `Encuestas`.`USUARIOS` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE INDEX `fk_Estudio_has_Usuarios_Usuarios1_idx` ON `Encuestas`.`ASIGNADOS` (`IdUsuarios` ASC) ;

CREATE INDEX `fk_Estudio_has_Usuarios_Estudio1_idx` ON `Encuestas`.`ASIGNADOS` (`IdEstudio` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`CUESTIONARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`CUESTIONARIOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`CUESTIONARIOS` (
  `IdCuestionario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cuestionario` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(250) NULL,
  `IdEstudio` INT NOT NULL,
  PRIMARY KEY (`IdCuestionario`),
  CONSTRAINT `fk_Cuestionario_Estudio1`
    FOREIGN KEY (`IdEstudio`)
    REFERENCES `Encuestas`.`ESTUDIOS` (`idEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `IdCuestionario_UNIQUE` ON `Encuestas`.`CUESTIONARIOS` (`IdCuestionario` ASC) ;

CREATE INDEX `fk_Cuestionario_Estudio1_idx` ON `Encuestas`.`CUESTIONARIOS` (`IdEstudio` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`TIPO_REACTIVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`TIPO_REACTIVO` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`TIPO_REACTIVO` (
  `TipoReactivo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TipoReactivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `Encuestas`.`REACTIVOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`REACTIVOS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`REACTIVOS` (
  `IdReactivo` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Reactivo` VARCHAR(100) NOT NULL,
  `TipoReactivo` VARCHAR(100) NOT NULL,
  `IdCuestionario` INT NOT NULL,
  PRIMARY KEY (`IdReactivo`),
  CONSTRAINT `fk_Reactivo_Cuestionario1`
    FOREIGN KEY (`IdCuestionario`)
    REFERENCES `Encuestas`.`CUESTIONARIOS` (`IdCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reactivo_Tipo_Reactivo1`
    FOREIGN KEY (`TipoReactivo`)
    REFERENCES `Encuestas`.`TIPO_REACTIVO` (`TipoReactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `IdCuestionario_UNIQUE` ON `Encuestas`.`REACTIVOS` (`IdReactivo` ASC) ;

CREATE INDEX `fk_Reactivo_Cuestionario1_idx` ON `Encuestas`.`REACTIVOS` (`IdCuestionario` ASC) ;

CREATE INDEX `fk_Reactivo_Tipo_Reactivo1_idx` ON `Encuestas`.`REACTIVOS` (`TipoReactivo` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`RESPUESTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`RESPUESTAS` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`RESPUESTAS` (
  `IdRespuesta` INT NOT NULL AUTO_INCREMENT,
  `Respuesta` VARCHAR(250) NULL,
  `IdReactivo` INT NOT NULL,
  PRIMARY KEY (`IdRespuesta`),
  CONSTRAINT `fk_Respuestas_Reactivo1`
    FOREIGN KEY (`IdReactivo`)
    REFERENCES `Encuestas`.`REACTIVOS` (`IdReactivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `IdCuestionario_UNIQUE` ON `Encuestas`.`RESPUESTAS` (`IdRespuesta` ASC) ;

CREATE INDEX `fk_Respuestas_Reactivo1_idx` ON `Encuestas`.`RESPUESTAS` (`IdReactivo` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`CUESTIONARIO_CONTESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`CUESTIONARIO_CONTESTADO` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`CUESTIONARIO_CONTESTADO` (
  `IdCuestionarioContestado` INT NOT NULL AUTO_INCREMENT,
  `IdEstudio` INT NOT NULL,
  `IdUsuarios` INT NOT NULL,
  `IdCuestionario` INT NOT NULL,
  PRIMARY KEY (`IdCuestionarioContestado`),
  CONSTRAINT `fk_Cuestionario_Contestado_Asignados1`
    FOREIGN KEY (`IdEstudio` , `IdUsuarios`)
    REFERENCES `Encuestas`.`ASIGNADOS` (`IdEstudio` , `IdUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuestionario_Contestado_Cuestionario1`
    FOREIGN KEY (`IdCuestionario`)
    REFERENCES `Encuestas`.`CUESTIONARIOS` (`IdCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE UNIQUE INDEX `IdCuestionarioContestado_UNIQUE` ON `Encuestas`.`CUESTIONARIO_CONTESTADO` (`IdCuestionarioContestado` ASC) ;

CREATE INDEX `fk_Cuestionario_Contestado_Asignados1_idx` ON `Encuestas`.`CUESTIONARIO_CONTESTADO` (`IdEstudio` ASC, `IdUsuarios` ASC) ;

CREATE INDEX `fk_Cuestionario_Contestado_Cuestionario1_idx` ON `Encuestas`.`CUESTIONARIO_CONTESTADO` (`IdCuestionario` ASC) ;


-- -----------------------------------------------------
-- Table `Encuestas`.`RESPUESTA_CAMPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encuestas`.`RESPUESTA_CAMPO` ;

CREATE TABLE IF NOT EXISTS `Encuestas`.`RESPUESTA_CAMPO` (
  `idRespuestaCampo` INT NOT NULL,
  `IdRespuesta` INT NOT NULL,
  `IdCuestionarioContestado` INT NOT NULL,
  PRIMARY KEY (`idRespuestaCampo`),
  CONSTRAINT `fk_Respuesta_Campo_Respuestas1`
    FOREIGN KEY (`IdRespuesta`)
    REFERENCES `Encuestas`.`RESPUESTAS` (`IdRespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Campo_Cuestionario_Contestado1`
    FOREIGN KEY (`IdCuestionarioContestado`)
    REFERENCES `Encuestas`.`CUESTIONARIO_CONTESTADO` (`IdCuestionarioContestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

CREATE INDEX `fk_Respuesta_Campo_Respuestas1_idx` ON `Encuestas`.`RESPUESTA_CAMPO` (`IdRespuesta` ASC) ;

CREATE INDEX `fk_Respuesta_Campo_Cuestionario_Contestado1_idx` ON `Encuestas`.`RESPUESTA_CAMPO` (`IdCuestionarioContestado` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Encuestas`.`TIPOUSUARIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `Encuestas`;
INSERT INTO `Encuestas`.`TIPOUSUARIO` (`Rol`) VALUES ('Administrador de Sistema');
INSERT INTO `Encuestas`.`TIPOUSUARIO` (`Rol`) VALUES ('Administrador de Estudio');
INSERT INTO `Encuestas`.`TIPOUSUARIO` (`Rol`) VALUES ('Encuestador');
INSERT INTO `Encuestas`.`TIPOUSUARIO` (`Rol`) VALUES ('Analista');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Encuestas`.`USUARIOS`
-- -----------------------------------------------------
START TRANSACTION;
USE `Encuestas`;
INSERT INTO `Encuestas`.`USUARIOS` (`Id`, `Nombre_Usuario`, `Correo`, `Contrasena`, `Rol`) VALUES (1, 'admin', 'admin@aleph.com', 'admin', 'Administrador de Sistema');

COMMIT;

